import { test as setup } from '@playwright/test';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  handlePostLoginChallenge,
  resolveChallengeMode,
  isInteractiveChallengeMode,
  resolveChallengeTimeoutMs,
} from './human-challenge';

/**
 * Auth Setup — generated by setup / env:edit
 *
 * Role "user" = default account for pipeline mode **general** (not an env role named general).
 * Login id resolve: LOGIN_ID_PREF → EMAIL → USERNAME → PHONE
 *
 * Human challenge (OTP/CAPTCHA): AUTH_CHALLENGE_MODE
 *   - otp-browser (disarankan) | otp-stdin | captcha-browser | auto | none
 *
 * File ini di-generate otomatis. Aman untuk diedit manual.
 * Jika selector form login tidak cocok, minta bantuan Hermes:
 *   "Tolong perbaiki src/support/auth.setup.ts untuk login page di {BASE_URL}/login"
 *
 * Jalankan: npm run auth:setup  |  npm run auth:setup:headed
 */

setup('authenticate:user', async ({ page }) => {
  const authFile = '.auth/local/user.json';
  const dir = path.dirname(authFile);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const pref = (process.env.TEST_USER_LOGIN_ID_PREF ?? '').trim().toLowerCase();
  const email = (process.env.TEST_USER_EMAIL ?? '').trim();
  const username = (process.env.TEST_USER_USERNAME ?? '').trim();
  const phone = (process.env.TEST_USER_PHONE ?? '').trim();
  const password = (process.env.TEST_USER_PASSWORD ?? '').trim();

  const loginId =
    (pref === 'email' && email) ||
    (pref === 'username' && username) ||
    (pref === 'phone' && phone) ||
    email ||
    username ||
    phone;

  if (!loginId || !password) {
    fs.writeFileSync(authFile, JSON.stringify({ cookies: [], origins: [] }, null, 2));
    console.log(
      'ℹ [Auth] user: missing login id or password — wrote empty storage. Set env keys (TEST_USER_*).',
    );
    return;
  }

  // Cek session masih valid
  if (fs.existsSync(authFile)) {
    try {
      await page.goto(process.env.BASE_URL! + '/dashboard');
      if (!page.url().includes('/login')) {
        console.log('✔ [Auth] Session user masih valid, skip login.');
        await page.context().storageState({ path: authFile });
        return;
      }
    } catch {
      console.log('⚠ [Auth] Gagal cek session user, login ulang...');
    }
  }

  await page.goto(process.env.BASE_URL! + '/login');

  // Satu field identity (email | username | phone) + password
  await page.fill(
    'input[type="email"], input[name="email"], input[name="username"], input[name="phone"], input[id*="email" i], input[id*="user" i], input[id*="phone" i]',
    loginId,
  );
  await page.fill('input[type="password"], input[name="password"], input[id*="pass" i]', password);
  await page.click(
    'button[type="submit"], input[type="submit"], button:has-text("Login"), button:has-text("Masuk"), button:has-text("Sign in"), button:has-text("Log in")',
  );

  const challengeMode = resolveChallengeMode();
  const successTimeout = isInteractiveChallengeMode(challengeMode)
    ? resolveChallengeTimeoutMs()
    : 20_000;
  try {
    const detected = await handlePostLoginChallenge(page, { mode: challengeMode });
    if (detected !== 'none') {
      console.log('ℹ [Auth] user: post-login challenge handled (' + detected + ')');
    }
    await page.waitForURL('**/dashboard**', { timeout: successTimeout });
    await page.context().storageState({ path: authFile });
    console.log('✔ [Auth] Session user tersimpan di', authFile);
  } catch (error) {
    if (isInteractiveChallengeMode(challengeMode)) {
      console.error(
        '✖ [Auth] user: assisted login failed (AUTH_CHALLENGE_MODE=' + challengeMode + ').',
        error instanceof Error ? error.message : error,
      );
    }
    throw error;
  }
});
