/**
 * Setup Wizard — environment file writer.
 *
 * Writes or merges `environments/{APP_ENV}.env` with role credentials,
 * BASE_URL, and challenge mode. Uses `normalizeWizardRoles()` for correct
 * env key mapping. Preserves existing keys not managed by the wizard.
 *
 * @module src/setup/wizard-writer
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { type AppEnv } from '../utils/app-env';
import { type ChallengeMode } from '../support/human-challenge';
import { type WizardRoleInput, normalizeWizardRoles } from '../shared/utils/role-credentials';

export interface EnvWriteOptions {
  appEnv: AppEnv;
  baseUrl: string;
  roles: WizardRoleInput[];
  challengeMode: ChallengeMode;
}

export interface EnvWriteResult {
  /** Absolute path of the written env file */
  envFilePath: string;
  /** Whether this was a new file or an update */
  isNewFile: boolean;
  /** Number of keys written/updated */
  keysWritten: number;
  /** Number of existing keys preserved */
  keysPreserved: number;
}

/** True when a value is dotenvx ciphertext (managed by env:edit, not the wizard). */
export function isEncryptedValue(v: string | undefined | null): boolean {
  return Boolean(v && v.trim().startsWith('encrypted:'));
}

/**
 * Read existing env file into a flat key-value map.
 * Returns null if the file does not exist.
 */
export function readExistingEnv(appEnv: AppEnv): Record<string, string> | null {
  const envPath = resolveEnvPath(appEnv);
  if (!fs.existsSync(envPath)) return null;

  const content = fs.readFileSync(envPath, 'utf-8');
  const map: Record<string, string> = {};

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIdx = trimmed.indexOf('=');
    if (eqIdx < 0) continue;

    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();

    // Remove surrounding quotes
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    map[key] = value;
  }

  return map;
}

/**
 * Write the env file with wizard-collected values.
 * Merges with existing values — wizard keys overwrite, non-wizard keys are preserved.
 */
export function writeEnvFile(options: EnvWriteOptions): EnvWriteResult {
  const { appEnv, baseUrl, roles, challengeMode } = options;
  const envPath = resolveEnvPath(appEnv);
  const isNewFile = !fs.existsSync(envPath);

  // Read existing values (for merge)
  const existing = readExistingEnv(appEnv) ?? {};
  const wizardKeys = new Set<string>();

  // Build new values from wizard inputs
  const newValues: Record<string, string> = {};

  // BASE_URL
  newValues['BASE_URL'] = baseUrl;
  wizardKeys.add('BASE_URL');

  // APP_ENV
  newValues['APP_ENV'] = appEnv;
  wizardKeys.add('APP_ENV');

  // AUTH_CHALLENGE_MODE
  newValues['AUTH_CHALLENGE_MODE'] = challengeMode;
  wizardKeys.add('AUTH_CHALLENGE_MODE');

  // HEADLESS (needed for challenge modes that need headed browser)
  if (
    challengeMode === 'otp-browser' ||
    challengeMode === 'captcha-browser' ||
    challengeMode === 'auto'
  ) {
    newValues['HEADLESS'] = 'false';
    wizardKeys.add('HEADLESS');
  } else {
    newValues['HEADLESS'] = 'true';
    wizardKeys.add('HEADLESS');
  }

  // Role credentials via normalizeWizardRoles
  const { envUpserts, warnings } = normalizeWizardRoles(roles);

  for (const [key, value] of Object.entries(envUpserts)) {
    newValues[key] = value;
    wizardKeys.add(key);
  }

  // Merge: wizard values overwrite, existing non-wizard keys preserved
  const merged: Record<string, string> = { ...existing, ...newValues };

  // Build env file content
  const lines: string[] = [];
  lines.push(`# Auto-generated by qa-playwright-kit setup wizard`);
  lines.push(`# Updated: ${new Date().toISOString()}`);
  lines.push(`# APP_ENV: ${appEnv}`);
  lines.push('');

  // Group: core config
  lines.push('# ─── Core Configuration ───────────────────────────');
  if (merged['APP_ENV']) lines.push(`APP_ENV=${merged['APP_ENV']}`);
  if (merged['BASE_URL']) lines.push(`BASE_URL=${merged['BASE_URL']}`);
  if (merged['HEADLESS']) lines.push(`HEADLESS=${merged['HEADLESS']}`);
  lines.push('');

  // Group: challenge mode
  lines.push('# ─── Auth Challenge ──────────────────────────────');
  if (merged['AUTH_CHALLENGE_MODE'])
    lines.push(`AUTH_CHALLENGE_MODE=${merged['AUTH_CHALLENGE_MODE']}`);
  if (merged['AUTH_CHALLENGE_TIMEOUT_MS'])
    lines.push(`AUTH_CHALLENGE_TIMEOUT_MS=${merged['AUTH_CHALLENGE_TIMEOUT_MS']}`);
  lines.push('');

  // Group: role credentials
  lines.push('# ─── Role Credentials ────────────────────────────');
  const rolePrefixes = new Set<string>();
  for (const key of Object.keys(merged)) {
    const m = /^([A-Z0-9_]+?)_(EMAIL|USERNAME|PHONE|PASSWORD|LOGIN_ID_PREF)$/.exec(key);
    if (m) rolePrefixes.add(m[1]);
  }

  // Always include TEST_USER first
  const orderedPrefixes = ['TEST_USER'];
  for (const prefix of rolePrefixes) {
    if (prefix !== 'TEST_USER') orderedPrefixes.push(prefix);
  }

  for (const prefix of orderedPrefixes) {
    const roleKeys = Object.keys(merged).filter(
      (k) =>
        k === `${prefix}_EMAIL` ||
        k === `${prefix}_USERNAME` ||
        k === `${prefix}_PHONE` ||
        k === `${prefix}_PASSWORD` ||
        k === `${prefix}_LOGIN_ID_PREF`,
    );
    if (roleKeys.length === 0) continue;

    lines.push(
      `# Role: ${prefix === 'TEST_USER' ? 'user' : prefix.toLowerCase().replace(/_/g, '-')}`,
    );
    for (const key of roleKeys.sort()) {
      lines.push(`${key}=${merged[key]}`);
    }
    lines.push('');
  }

  // Group: other existing keys not managed by wizard
  const roleKeyPattern = /^[A-Z0-9_]+_(EMAIL|USERNAME|PHONE|PASSWORD|LOGIN_ID_PREF)$/;
  const otherKeys = Object.keys(merged).filter(
    (k) => !wizardKeys.has(k) && !k.startsWith('DOTENV_') && !roleKeyPattern.test(k),
  );
  if (otherKeys.length > 0) {
    lines.push('# ─── Other (preserved) ──────────────────────────');
    for (const key of otherKeys.sort()) {
      lines.push(`${key}=${merged[key]}`);
    }
    lines.push('');
  }

  // Ensure directory exists
  const dir = path.dirname(envPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(envPath, lines.join('\n'), 'utf-8');

  // Log warnings from normalizeWizardRoles
  for (const w of warnings) {
    console.warn(`⚠ ${w}`);
  }

  return {
    envFilePath: envPath,
    isNewFile,
    keysWritten: wizardKeys.size,
    keysPreserved: otherKeys.length,
  };
}

/**
 * Resolve the env file path for a given APP_ENV.
 * Canonical location is config/environments/ (ARCH-002). Legacy
 * environments/ is a read-only migration fallback for pre-existing files;
 * NEW files are always written to the canonical config/environments/.
 */
export function resolveEnvPath(appEnv: AppEnv): string {
  // Find repo root by climbing up from cwd
  const repoRoot = findRepoRoot();
  const configPath = path.join(repoRoot, 'config', 'environments', `${appEnv}.env`);
  if (fs.existsSync(configPath)) return configPath;
  const legacyPath = path.join(repoRoot, 'environments', `${appEnv}.env`);
  if (fs.existsSync(legacyPath)) return legacyPath;
  return configPath;
}

/**
 * Find repository root by looking for package.json.
 */
function findRepoRoot(): string {
  let dir = process.cwd();
  for (let i = 0; i < 12; i += 1) {
    if (fs.existsSync(path.join(dir, 'package.json'))) {
      return dir;
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return process.cwd();
}
